export const KROOMBOX = {
  name: 'Kroombox',
  tagline: 'Hosting infrastructure, reimagined.',
  description: 'Kroombox adalah platform hosting modern yang fokus pada kecepatan, transparansi biaya, dan keberlanjutan energi.',
  founded: '2024',
  hq: 'Jakarta, Indonesia',
  email: 'halo@kroombox.com',
  stats: { uptime: '99.98%', clients: '1.240+', dataCenters: 4, renewable: '83%' },
  members: [
    { id: 'arda-pratama', name: 'Arda Pratama', role: 'Founder & CEO', avatar: 'AP', avatarUrl: 'image/avatars/avatar_arda_pratama_1784178395105.png', joined: 'Jan 2024', location: 'Jakarta', color: '#2563eb', color2: '#3b82f6', initials: 'AP', focus: 'Visi produk, fundraising, kemitraan strategis.', bio: 'Membangun Kroombox dari garasi dengan misi menjadikan hosting se-transparan listrik PLN.', quote: '"Hosting seharusnya transparan seperti tagihan listrik."', github: 'ardapratama', linkedin: 'ardapratama', instagram: 'arda.p', tasks: ['Menyusun roadmap produk 2024-2026', 'Negosiasi seed round dengan 3 VC', 'Merekrut core team awal'], achievements: ['Seed funding 1.2M USD (Q2 2024)', 'Pemenang Startup Terbaik ID-TECH 2024', 'Menggaet 120+ klien awal dalam 6 bulan'], skills: ['Strategy', 'Fundraising', 'Public Speaking'], metric: { label: 'Klien ditandatangani', value: '124' } },
    { id: 'sasha-wijaya', name: 'Sasha Wijaya', role: 'Co-Founder & CTO', avatar: 'SW', avatarUrl: 'image/avatars/avatar_sasha_wijaya_1784178405448.png', joined: 'Jan 2024', location: 'Bandung', color: '#0ea5e9', color2: '#38bdf8', initials: 'SW', focus: 'Arsitektur cloud, edge network, keamanan.', bio: 'Ex-infrastructure engineer yang lelah dengan dashboard cloud yang bloated.', quote: '"Engineering adalah seni menyederhanakan kompleksitas."', github: 'sashawijaya', linkedin: 'sashawijaya', instagram: 'sasha.dev', tasks: ['Merancang arsitektur multi-region', 'Membangun panel kontrol internal', 'Audit keamanan triwulan'], achievements: ['Migrasi 100% ke Kubernetes tanpa downtime', 'Waktu deploy turun dari 12 mnt ke 47 dtk', 'Sertifikasi ISO 27001 di pipeline'], skills: ['Kubernetes', 'Rust', 'Security', 'DevOps'], metric: { label: 'Uptime rata-rata', value: '99.98%' } },
    { id: 'nadia-putri', name: 'Nadia Putri', role: 'Head of Product', avatar: 'NP', avatarUrl: 'image/avatars/avatar_nadia_putri_1784178415412.png', joined: 'Mar 2024', location: 'Jakarta', color: '#06b6d4', color2: '#22d3ee', initials: 'NP', focus: 'Riset pengguna, product-market fit, onboarding.', bio: 'Spesialis UX yang memastikan setiap klik terasa ringan dan jelas.', quote: '"Setiap klik harus terasa ringan dan jelas."', github: 'nadiaputri', linkedin: 'nadiaputri', instagram: 'nadia.ui', tasks: ['Riset pengguna mingguan', 'Menulis spesifikasi fitur baru', 'Memimpin sprint planning'], achievements: ['Onboarding completion naik 38%', 'Mengurangi support ticket 42%', 'Meluncurkan 14 iterasi dashboard'], skills: ['UX Research', 'Figma', 'Analytics', 'Writing'], metric: { label: 'NPS skor', value: '72' } },
    { id: 'riza-hakim', name: 'Riza Hakim', role: 'Lead Backend Engineer', avatar: 'RH', avatarUrl: 'image/avatars/avatar_riza_hakim_1784178425059.png', joined: 'Apr 2024', location: 'Yogyakarta', color: '#1e40af', color2: '#3b82f6', initials: 'RH', focus: 'API gateway, billing engine, database scaling.', bio: 'Suka debugging di jam 3 pagi dan menegur orang yang commit tanpa test.', quote: '"Code yang tidak dites adalah hutang teknis."', github: 'rizahakim', linkedin: 'rizahakim', instagram: 'riza.dev', tasks: ['Membangun sistem billing per-jam', 'Optimasi query Postgres', 'On-call rotation 24/7'], achievements: ['Menurunkan p95 latency dari 480ms ke 89ms', 'Billing akurat 99.97% selama 9 bulan', 'Internal CLI tool dipakai 100% tim'], skills: ['Go', 'Postgres', 'Redis', 'gRPC'], metric: { label: 'Endpoint ter-ship', value: '237' } },
    { id: 'elena-santoso', name: 'Elena Santoso', role: 'Frontend Engineer', avatar: 'ES', avatarUrl: 'image/avatars/avatar_elena_santoso_1784178445923.png', joined: 'May 2024', location: 'Surabaya', color: '#4f46e5', color2: '#6366f1', initials: 'ES', focus: 'Design system, dashboard, micro-interactions.', bio: 'Percaya bahwa dark mode bukan gaya hidup, tapi kebutuhan.', quote: '"Pixel yang rapi adalah bentuk penghormatan ke pengguna."', github: 'elenasantoso', linkedin: 'elenasantoso', instagram: 'elena.ui', tasks: ['Membangun design system Kroombox', 'Mengerjakan halaman billing & usage', 'Migrasi ke React 19'], achievements: ['Design system dipakai di 17 produk internal', 'Lighthouse score rata-rata 96', 'Bundle size turun 41% dalam 3 bulan'], skills: ['React', 'TypeScript', 'CSS', 'Motion'], metric: { label: 'Komponen ter-bangun', value: '84' } },
    { id: 'bima-ardy', name: 'Bima Ardy', role: 'DevOps & SRE', avatar: 'BA', avatarUrl: 'image/avatars/avatar_bima_ardy_1784178456041.png', joined: 'Jun 2024', location: 'Denpasar', color: '#0284c7', color2: '#0ea5e9', initials: 'BA', focus: 'CI/CD, observability, incident response.', bio: 'Otak di balik status page hijau yang membuat pelanggan percaya.', quote: '"Jika tidak bisa diukur, berarti itu tidak ada."', github: 'bimaardy', linkedin: 'bimaardy', instagram: 'bima.ops', tasks: ['Membangun pipeline GitOps', 'Setup Grafana + Prometheus stack', 'Menulis runbook untuk SRE'], achievements: ['MTTR turun ke 7 menit', 'Deployment 30x/hari tanpa rollback', 'Insiden P0 nol dalam 8 bulan'], skills: ['Terraform', 'Prometheus', 'AWS', 'Bash'], metric: { label: 'Deploy per hari', value: '30' } },
    { id: 'clarissa-tan', name: 'Clarissa Tan', role: 'Customer Success Lead', avatar: 'CT', avatarUrl: '', joined: 'Jul 2024', location: 'Jakarta', color: '#0d9488', color2: '#14b8a6', initials: 'CT', focus: 'Onboarding klien, edukasi, retention.', bio: 'Mantan sysadmin yang sekarang gemar menjelaskan SSL lewat analogi kopi.', quote: '"Sukses klien adalah kesuksesan kita bersama."', github: 'clarissatan', linkedin: 'clarissatan', instagram: 'clarissa.cs', tasks: ['Membangun knowledge base publik', 'Menyusun onboarding 7-hari', 'Mengelola komunitas Discord'], achievements: ['Churn rate turun dari 6.2% ke 1.4%', 'Membuat 42 video tutorial', 'CSAT 4.8/5 selama 4 kuartal'], skills: ['Support', 'Docs', 'Community', 'Empathy'], metric: { label: 'Klien terselamatkan', value: '58' } },
    { id: 'farel-oka', name: 'Farel Oka', role: 'Sustainability & Green Ops', avatar: 'FO', avatarUrl: '', joined: 'Sep 2024', location: 'Medan', color: '#0f766e', color2: '#14b8a6', initials: 'FO', focus: 'Energi terbarukan, carbon reporting, efisiensi PUE.', bio: 'Bikin data center bisa nyanyi lagu hijau tanpa ironi.', quote: '"Teknologi harus memberi kembali ke planet ini."', github: 'fareloka', linkedin: 'fareloka', instagram: 'farel.green', tasks: ['Audit konsumsi energi per region', 'Negosiasi PPA panel surya', 'Laporan keberlanjutan triwulan'], achievements: ['Renewable mix naik dari 41% ke 83%', 'PUE turun ke 1.18 di region Jakarta', 'Laporan ESG pertama dipublikasikan'], skills: ['Energy', 'Data', 'Reporting', 'Negotiation'], metric: { label: 'Energi terbarukan', value: '83%' } }
  ],
  partners: [
    { name: 'NusaCloud', type: 'Cloud Provider' },
    { name: 'AtapID VC', type: 'Investor' },
    { name: 'Hijau Daya', type: 'Energy Partner' },
    { name: 'Kabel.net', type: 'Network Partner' },
    { name: 'Pelita Data', type: 'Datacenter' },
    { name: 'KampusDev', type: 'Community' }
  ],
  partnerLogos: [
    { src: 'image/partner/logo_kroombox.png', alt: 'Kroombox' },
    { src: 'image/partner/logo_kroombox_new.png', alt: 'Kroombox New' },
    { src: 'image/partner/logo_kroombase.png', alt: 'Kroombase' },
    { src: 'image/partner/logo_kroombridge.png', alt: 'Kroombridge' },
    { src: 'image/partner/logo_kroomoney.png', alt: 'Kroomoney' },
    { src: 'image/partner/logo_kroma.png', alt: 'Kroma' },
    { src: 'image/partner/logo_kroma-k.png', alt: 'Kroma K' },
    { src: 'image/partner/logo_giat.png', alt: 'Giat' },
    { src: 'image/partner/logo_uni.png', alt: 'Uni' },
    { src: 'image/partner/logo_universe.png', alt: 'Universe' },
    { src: 'image/partner/logo-bpa.png', alt: 'BPA' },
    { src: 'image/partner/logo_KHB.png', alt: 'KHB' },
    { src: 'image/partner/logo_keuangan_KHB.png', alt: 'Keuangan KHB' },
    { src: 'image/partner/logo_aquasmartponik.png', alt: 'Aquasmartponik' },
    { src: 'image/partner/logo_autocashier.png', alt: 'Autocashier' },
    { src: 'image/partner/logo_jagoai.jpeg', alt: 'JagoAI' },
    { src: 'image/partner/logo_jagocv.png', alt: 'JagoCV' },
    { src: 'image/partner/logo_kampung_sorgum.jpg', alt: 'Kampung Sorgum' },
    { src: 'image/partner/logo_khoir_quest.png', alt: 'Khoir Quest' },
    { src: 'image/partner/logo_kolab.jpg', alt: 'Kolab' },
    { src: 'image/partner/logo_kwt_dwisri.png', alt: 'KWT Dwisri' },
    { src: 'image/partner/logo_kwt_melati.jpg', alt: 'KWT Melati' },
    { src: 'image/partner/logo_ngolab.jpeg', alt: 'Ngolab' },
    { src: 'image/partner/logo_paud_Husnul.png', alt: 'PAUD Husnul' },
    { src: 'image/partner/logo_sentra_kreasi.png', alt: 'Sentra Kreasi' },
    { src: 'image/partner/logo_gmps.png', alt: 'GMPS' }
  ],
  social: [
    { label: 'LinkedIn', url: 'https://linkedin.com/company/kroombox', icon: 'linkedin' },
    { label: 'Instagram', url: 'https://instagram.com/kroombox', icon: 'instagram' },
    { label: 'TikTok', url: 'https://tiktok.com/@kroombox', icon: 'tiktok' },
    { label: 'Email', url: 'mailto:halo@kroombox.com', icon: 'email' },
    { label: 'GitHub', url: 'https://github.com/kroombox', icon: 'github' }
  ]
};
