export const KROOMBOX = {
  name: 'Kroombox',
  tagline: 'Hosting infrastructure, reimagined.',
  description: 'Kroombox adalah platform hosting modern yang fokus pada kecepatan, transparansi biaya, dan keberlanjutan energi.',
  founded: '2024',
  hq: 'Jakarta, Indonesia',
  stats: { uptime: '99.98%', clients: '1.240+', dataCenters: 4, renewable: '83%' },
  members: [
    { id: 'arda-pratama', name: 'Arda Pratama', role: 'Founder & CEO', avatar: 'AP', joined: 'Jan 2024', location: 'Jakarta', color: '#2563eb', color2: '#3b82f6', initials: 'AP', focus: 'Visi produk, fundraising, kemitraan strategis.', bio: 'Membangun Kroombox dari garasi dengan misi menjadikan hosting se-transparan listrik PLN.', tasks: ['Menyusun roadmap produk 2024-2026', 'Negosiasi seed round dengan 3 VC', 'Merekrut core team awal'], achievements: ['Seed funding 1.2M USD (Q2 2024)', 'Pemenang Startup Terbaik ID-TECH 2024', 'Menggaet 120+ klien awal dalam 6 bulan'], skills: ['Strategy', 'Fundraising', 'Public Speaking'], metric: { label: 'Klien ditandatangani', value: '124' } },
    { id: 'sasha-wijaya', name: 'Sasha Wijaya', role: 'Co-Founder & CTO', avatar: 'SW', joined: 'Jan 2024', location: 'Bandung', color: '#0ea5e9', color2: '#38bdf8', initials: 'SW', focus: 'Arsitektur cloud, edge network, keamanan.', bio: 'Ex-infrastructure engineer yang lelah dengan dashboard cloud yang bloated.', tasks: ['Merancang arsitektur multi-region', 'Membangun panel kontrol internal', 'Audit keamanan triwulan'], achievements: ['Migrasi 100% ke Kubernetes tanpa downtime', 'Waktu deploy turun dari 12 mnt ke 47 dtk', 'Sertifikasi ISO 27001 di pipeline'], skills: ['Kubernetes', 'Rust', 'Security', 'DevOps'], metric: { label: 'Uptime rata-rata', value: '99.98%' } },
    { id: 'nadia-putri', name: 'Nadia Putri', role: 'Head of Product', avatar: 'NP', joined: 'Mar 2024', location: 'Jakarta', color: '#06b6d4', color2: '#22d3ee', initials: 'NP', focus: 'Riset pengguna, product-market fit, onboarding.', bio: 'Spesialis UX yang memastikan setiap klik terasa ringan dan jelas.', tasks: ['Riset pengguna mingguan', 'Menulis spesifikasi fitur baru', 'Memimpin sprint planning'], achievements: ['Onboarding completion naik 38%', 'Mengurangi support ticket 42%', 'Meluncurkan 14 iterasi dashboard'], skills: ['UX Research', 'Figma', 'Analytics', 'Writing'], metric: { label: 'NPS skor', value: '72' } },
    { id: 'riza-hakim', name: 'Riza Hakim', role: 'Lead Backend Engineer', avatar: 'RH', joined: 'Apr 2024', location: 'Yogyakarta', color: '#1e40af', color2: '#3b82f6', initials: 'RH', focus: 'API gateway, billing engine, database scaling.', bio: 'Suka debugging di jam 3 pagi dan menegur orang yang commit tanpa test.', tasks: ['Membangun sistem billing per-jam', 'Optimasi query Postgres', 'On-call rotation 24/7'], achievements: ['Menurunkan p95 latency dari 480ms ke 89ms', 'Billing akurat 99.97% selama 9 bulan', 'Internal CLI tool dipakai 100% tim'], skills: ['Go', 'Postgres', 'Redis', 'gRPC'], metric: { label: 'Endpoint ter-ship', value: '237' } },
    { id: 'elena-santoso', name: 'Elena Santoso', role: 'Frontend Engineer', avatar: 'ES', joined: 'May 2024', location: 'Surabaya', color: '#4f46e5', color2: '#6366f1', initials: 'ES', focus: 'Design system, dashboard, micro-interactions.', bio: 'Percaya bahwa dark mode bukan gaya hidup, tapi kebutuhan.', tasks: ['Membangun design system Kroombox', 'Mengerjakan halaman billing & usage', 'Migrasi ke React 19'], achievements: ['Design system dipakai di 17 produk internal', 'Lighthouse score rata-rata 96', 'Bundle size turun 41% dalam 3 bulan'], skills: ['React', 'TypeScript', 'CSS', 'Motion'], metric: { label: 'Komponen ter-bangun', value: '84' } },
    { id: 'bima-ardy', name: 'Bima Ardy', role: 'DevOps & SRE', avatar: 'BA', joined: 'Jun 2024', location: 'Denpasar', color: '#0284c7', color2: '#0ea5e9', initials: 'BA', focus: 'CI/CD, observability, incident response.', bio: 'Otak di balik status page hijau yang membuat pelanggan percaya.', tasks: ['Membangun pipeline GitOps', 'Setup Grafana + Prometheus stack', 'Menulis runbook untuk SRE'], achievements: ['MTTR turun ke 7 menit', 'Deployment 30x/hari tanpa rollback', 'Insiden P0 nol dalam 8 bulan'], skills: ['Terraform', 'Prometheus', 'AWS', 'Bash'], metric: { label: 'Deploy per hari', value: '30' } },
    { id: 'clarissa-tan', name: 'Clarissa Tan', role: 'Customer Success Lead', avatar: 'CT', joined: 'Jul 2024', location: 'Jakarta', color: '#0d9488', color2: '#14b8a6', initials: 'CT', focus: 'Onboarding klien, edukasi, retention.', bio: 'Mantan sysadmin yang sekarang gemar menjelaskan SSL lewat analogi kopi.', tasks: ['Membangun knowledge base publik', 'Menyusun onboarding 7-hari', 'Mengelola komunitas Discord'], achievements: ['Churn rate turun dari 6.2% ke 1.4%', 'Membuat 42 video tutorial', 'CSAT 4.8/5 selama 4 kuartal'], skills: ['Support', 'Docs', 'Community', 'Empathy'], metric: { label: 'Klien terselamatkan', value: '58' } },
    { id: 'farel-oka', name: 'Farel Oka', role: 'Sustainability & Green Ops', avatar: 'FO', joined: 'Sep 2024', location: 'Medan', color: '#0f766e', color2: '#14b8a6', initials: 'FO', focus: 'Energi terbarukan, carbon reporting, efisiensi PUE.', bio: 'Bikin data center bisa nyanyi lagu hijau tanpa ironi.', tasks: ['Audit konsumsi energi per region', 'Negosiasi PPA panel surya', 'Laporan keberlanjutan triwulan'], achievements: ['Renewable mix naik dari 41% ke 83%', 'PUE turun ke 1.18 di region Jakarta', 'Laporan ESG pertama dipublikasikan'], skills: ['Energy', 'Data', 'Reporting', 'Negotiation'], metric: { label: 'Energi terbarukan', value: '83%' } }
  ],
  partners: [
    { name: 'NusaCloud', type: 'Cloud Provider' },
    { name: 'AtapID VC', type: 'Investor' },
    { name: 'Hijau Daya', type: 'Energy Partner' },
    { name: 'Kabel.net', type: 'Network Partner' },
    { name: 'Pelita Data', type: 'Datacenter' },
    { name: 'KampusDev', type: 'Community' }
  ]
};
